### ISSUE TITLE
JWT token timing issues

### ISSUE THREAD

**Issue by hostalp** [camunda/camunda-platform#127]
We've deployed the Camunda Platform 8.2.0 at Kubernetes via the official Helm chart https://github.com/camunda/camunda-platform-helm/tree/main/charts/camunda-platform
We used the combined Ingress setup scenario described at https://docs.camunda.io/docs/self-managed/platform-deployment/helm-kubernetes/guides/ingress-setup/#combined-ingress-setup

Everything is running but there are random (but frequent) authentication issues that appear to be related to the JWT token validity.
When accessing the **operate** or **identity** components unauthenticated, user is redirected to the Keycloak to perform login. After entering valid credentials and redirecting back (to operate or identity) the user ends up at the _noPermission_ (operate) or _unauthorized_ (identity) page in approx. 80-90% cases. In the remaining cases the user is able to access the desired resource as expected.

After inspecting logs we found out the following in the **operate** log in such cases:
```
2023-04-27 15:20:27.474 DEBUG 7 --- [nio-8080-exec-8] i.c.o.w.s.i.IdentityController           : Called back by identity with /operate/identity-callback state=&session_state=30d1208a-e017-469c-a367-bc42a55467bb&code=dd0f8e38-a70e-4c87-b84c-7748fdf10421.30d1208a-e017-469c-a367-bc42a55467bb.4024fa3e-55a9-4f83-9775-8336558985d7, SessionId: F92F92ADD5504B3C95631D77B9814A28 and AuthCode dd0f8e38-a70e-4c87-b84c-7748fdf10421.30d1208a-e017-469c-a367-bc42a55467bb.4024fa3e-55a9-4f83-9775-8336558985d7
2023-04-27 15:20:27.485 ERROR 7 --- [nio-8080-exec-8] i.c.o.w.s.i.IdentityController           : Error in authentication callback:

io.camunda.identity.sdk.authentication.exception.InvalidClaimException: the provided claims are invalid
        at io.camunda.identity.sdk.authentication.AbstractAuthentication.verifyToken(AbstractAuthentication.java:133) ~[identity-sdk-8.2.0.jar!/:?]
        at io.camunda.identity.sdk.authentication.AbstractAuthentication.verifyToken(AbstractAuthentication.java:103) ~[identity-sdk-8.2.0.jar!/:?]
        at jdk.internal.reflect.GeneratedMethodAccessor67.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at io.camunda.identity.sdk.annotation.AnnotationProcessor.lambda$apply$0(AnnotationProcessor.java:33) ~[identity-sdk-8.2.0.jar!/:?]
        at jdk.proxy2.$Proxy141.verifyToken(Unknown Source) ~[?:?]
        at io.camunda.operate.webapp.security.identity.IdentityAuthentication.authenticate(IdentityAuthentication.java:139) ~[classes!/:?]
        at io.camunda.operate.webapp.security.identity.IdentityService.getAuthenticationFor(IdentityService.java:75) ~[classes!/:?]
        at io.camunda.operate.webapp.security.identity.IdentityController.loggedInCallback(IdentityController.java:81) ~[classes!/:?]
        ...
Caused by: com.auth0.jwt.exceptions.IncorrectClaimException: The Token can't be used before 2023-04-27T15:20:28Z.
        at com.auth0.jwt.JWTVerifier$BaseVerification.assertValidInstantClaim(JWTVerifier.java:352) ~[java-jwt-4.3.0.jar!/:4.3.0]
        at com.auth0.jwt.JWTVerifier$BaseVerification.lambda$addMandatoryClaimChecks$19(JWTVerifier.java:313) ~[java-jwt-4.3.0.jar!/:4.3.0]
        at com.auth0.jwt.JWTVerifier$BaseVerification$1.verify(JWTVerifier.java:405) ~[java-jwt-4.3.0.jar!/:4.3.0]
        at com.auth0.jwt.JWTVerifier.verifyClaims(JWTVerifier.java:482) ~[java-jwt-4.3.0.jar!/:4.3.0]
        at com.auth0.jwt.JWTVerifier.verify(JWTVerifier.java:464) ~[java-jwt-4.3.0.jar!/:4.3.0]
        at io.camunda.identity.sdk.authentication.AbstractAuthentication.verify(AbstractAuthentication.java:147) ~[identity-sdk-8.2.0.jar!/:?]
        at io.camunda.identity.sdk.authentication.AbstractAuthentication.verifyToken(AbstractAuthentication.java:126) ~[identity-sdk-8.2.0.jar!/:?]
        ... 131 more
```
Which looks like a timing issue as the timestamp in `The Token can't be used before 2023-04-27T15:20:28Z` happens to be of slightly later time than the timestamp of the request as captured in the log: `15:20:27.474`
After inspecting the pods, where they run and what's the time at these hosts there are really some minor (somewhere between 0-1s) differences that explain this behavior. We'll try to get our provider to ensure the time synchronization at these hosts which should help.

However there may be still some differences in some cases and then it would be useful to be able to tolerate bigger time differences.
We tried to find such configuration option for Camunda, but to no avail.

Is there anything like this possible (extending the JWT token leeway setting at the components that use it)?
If not, could it be added?

**Comment by jessesimpson36** [comment]
This issue seems more relevant to https://github.com/camunda/camunda-platform-helm .
This repo is intended for the docker-compose method of deploying for development. I'll see if I can transfer the issue.
