### ISSUE TITLE
i.c.o.z.ImportJob  : Import is not possible for Zeebe version: 8.0

### ISSUE THREAD

**Issue by domaroff** [camunda/camunda-platform#5]
Self managed docker-compose based installation slightly changed for arm64 platform.
Everything is starting perfectly and working until I try to deploy bpmn process.
Deployment via Modeler returns OK, but I cannot see any deployments in Operate and see this error in log (probably operate-importer-1.3.4.jar is wrong version for Platform 8.0) :

operate          | io.camunda.operate.exceptions.OperateRuntimeException: Import is not possible for Zeebe version: 8.0
operate          | 	at io.camunda.operate.zeebeimport.ImportBatchProcessorFactory.getImportBatchProcessor(ImportBatchProcessorFactory.java:40) ~[operate-importer-1.3.4.jar!/:?]
operate          | 	at io.camunda.operate.zeebeimport.ImportJob.processOneIndexBatch(ImportJob.java:115) ~[operate-importer-1.3.4.jar!/:?]
operate          | 	at io.camunda.operate.zeebeimport.ImportJob.call(ImportJob.java:80) ~[operate-importer-1.3.4.jar!/:?]
operate          | 	at io.camunda.operate.zeebeimport.RecordsReader.lambda$scheduleImport$2(RecordsReader.java:249) ~[operate-importer-1.3.4.jar!/:?]
operate          | 	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
operate          | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
operate          | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
operate          | 	at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by domaroff** [comment]
Sorry, my fault. Misconfig in compose file
