### ISSUE TITLE
Connectors: repetitive authentication errors in identity-based bundle

### ISSUE THREAD

**Issue by igpetrov** [camunda/camunda-platform#87]
## Description

Customer [has reported](https://camunda-platform.slack.com/archives/C0497FR8XML/p1676483564281879?thread_ts=1675068074.845339&cid=C0497FR8XML) that they observe repetitive stack traces thrown into logs every 5 minutes and sometimes often.

```
2023-02-15 17:20:25.797 ERROR 1 --- [pool-2-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
io.camunda.operate.exception.OperateException: Authentication error : 401
2023-02-15 17:20:30.884 ERROR 1 --- [pool-2-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
io.camunda.operate.exception.OperateException: Authentication error : 401
2023-02-15 17:25:33.253 ERROR 1 --- [pool-2-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
io.camunda.operate.exception.OperateException: Authentication error : 401
2023-02-15 17:25:38.354 ERROR 1 --- [pool-2-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
io.camunda.operate.exception.OperateException: Authentication error : 401
2023-02-15 17:30:40.697 ERROR 1 --- [pool-2-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
io.camunda.operate.exception.OperateException: Authentication error : 401
2023-02-15 17:36:07.686 ERROR 1 --- [pool-2-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
io.camunda.operate.exception.OperateException: Authentication error : 401
2023-02-15 17:41:09.176 ERROR 1 --- [pool-2-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
io.camunda.operate.exception.OperateException: Authentication error : 401
2023-02-15 17:41:14.252 ERROR 1 --- [pool-2-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
io.camunda.operate.exception.OperateException: Authentication error : 401
2023-02-15 17:46:15.628 ERROR 1 --- [pool-2-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
io.camunda.operate.exception.OperateException: Authentication error : 401
2023-02-15 17:46:20.746 ERROR 1 --- [pool-2-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
io.camunda.operate.exception.OperateException: Authentication error : 401
2023-02-15 17:51:22.186 ERROR 1 --- [pool-2-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
io.camunda.operate.exception.OperateException: Authentication error : 401
2023-02-15 17:51:27.264 ERROR 1 --- [pool-2-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
io.camunda.operate.exception.OperateException: Authentication error : 401
```

I was able to reproduce the same behavior, however there is no consistent pattern:

```
2023-02-16 15:13:58 2023-02-16 13:13:58.223 ERROR 1 --- [pool-2-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
2023-02-16 15:13:58 
2023-02-16 15:13:58 io.camunda.operate.exception.OperateException: Authentication error : 401 
2023-02-16 15:13:58     at io.camunda.operate.CamundaOperateClient.execute(CamundaOperateClient.java:91)
2023-02-16 15:13:58     at io.camunda.operate.CamundaOperateClient.executeQuery(CamundaOperateClient.java:189)
2023-02-16 15:13:58     at io.camunda.operate.CamundaOperateClient.search(CamundaOperateClient.java:163)
2023-02-16 15:13:58     at io.camunda.operate.CamundaOperateClient.searchProcessDefinitions(CamundaOperateClient.java:50)
2023-02-16 15:13:58     at io.camunda.connector.runtime.inbound.operate.OperateClientLifecycle.searchProcessDefinitions(OperateClientLifecycle.java:117)
2023-02-16 15:13:58     at io.camunda.connector.runtime.inbound.importer.ProcessDefinitionImporter.scheduleImport(ProcessDefinitionImporter.java:63)
2023-02-16 15:13:58     at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
2023-02-16 15:13:58     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2023-02-16 15:13:58     at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2023-02-16 15:13:58     at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
2023-02-16 15:13:58     at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
2023-02-16 15:13:58     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
2023-02-16 15:13:58     at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
2023-02-16 15:13:58     at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
2023-02-16 15:13:58     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2023-02-16 15:13:58     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2023-02-16 15:13:58     at java.base/java.lang.Thread.run(Unknown Source)
```

## Impact

Inbound webhook still operates fine, however log errors are annoying. (to be confirmed)

## Steps to reproduce

1. `docker-compose -f docker-compose.yaml up`
2. Wait for 5+ minutes. See logs via Docker Desktop or other means.

**Comment by igpetrov** [comment]
Seeing periodical in k8s cluster as well

```
2023-03-30 09:10:26.766 ERROR 1 --- [pool-2-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

io.camunda.operate.exception.OperateException: Authentication error : 401 
        at io.camunda.operate.CamundaOperateClient.execute(CamundaOperateClient.java:91)
        at io.camunda.operate.CamundaOperateClient.executeQuery(CamundaOperateClient.java:189)
        at io.camunda.operate.CamundaOperateClient.search(CamundaOperateClient.java:163)
        at io.camunda.operate.CamundaOperateClient.searchProcessDefinitions(CamundaOperateClient.java:50)
        at io.camunda.connector.runtime.inbound.operate.OperateClientLifecycle.searchProcessDefinitions(OperateClientLifecycle.java:117)
        at io.camunda.connector.runtime.inbound.importer.ProcessDefinitionImporter.scheduleImport(ProcessDefinitionImporter.java:63)
        at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```
