### ISSUE TITLE
Exception on MULTI_TENANCY_ENABLED

### ISSUE THREAD

**Issue by cooperlyt** [camunda/camunda-platform#920]
1. Download this project
2. change `MULTI_TENANCY_ENABLED=true ` in .env file
3. run `docker compose up`  
4. in the  connectors service log will get exception:
```
2024-10-03 16:16:10 io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Expected to handle gRPC request ActivateJobs with tenant identifier '<default>', but tenant could not be retrieved from the request context
2024-10-03 16:16:10     at io.grpc.Status.asRuntimeException(Status.java:533)
2024-10-03 16:16:10     at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481)
2024-10-03 16:16:10     at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:564)
2024-10-03 16:16:10     at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:72)
2024-10-03 16:16:10     at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:729)
2024-10-03 16:16:10     at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:710)
2024-10-03 16:16:10     at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
2024-10-03 16:16:10     at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
2024-10-03 16:16:10     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2024-10-03 16:16:10     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2024-10-03 16:16:10     at java.base/java.lang.Thread.run(Unknown Source)
```

What's I miss?

**Comment by cooperlyt** [comment]
It's my fault; I overlooked the comments in the environment variables:
```
# This requires use of identity for authentication
#
# ZEEBE_AUTHENTICATION_MODE=identity
# 
```
